# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end

  # App Lovin Mediation Adapters
  # https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/master/applovin_max/CHANGELOG.md
  # Supported Version https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/master/applovin_max/ios/applovin_max.podspec#L21
  pod 'AppLovinSDK', '13.0.0'
  # https://developers.applovin.com/en/max/flutter/preparing-mediated-networks#adapter-network-information-1
  pod 'AppLovinMediationGoogleAdapter', '11.11.0.0'           # AdMob
  pod 'AppLovinMediationFyberAdapter', '8.3.2.1'              # DT Exchange
  pod 'AppLovinMediationGoogleAdManagerAdapter', '11.11.0.0'  # Google Ad Manager
  pod 'AppLovinMediationInMobiAdapter', '10.7.8.0'            # InMobi
  pod 'AppLovinMediationIronSourceAdapter', '8.4.0.0.0'       # ironSource
  pod 'AppLovinMediationVungleAdapter', '7.4.2.0'             # Liftoff Monetize
  pod 'AppLovinMediationFacebookAdapter', '6.15.2.1'          # Meta
  pod 'AppLovinMediationMintegralAdapter', '7.7.3.0.0'        # Mintegral
  pod 'AppLovinMediationMobileFuseAdapter', '1.8.0.1'         # MobileFuse
  pod 'AppLovinMediationSmaatoAdapter', '22.9.1.0'            # Smaato
  pod 'AppLovinMediationUnityAdsAdapter', '4.12.4.0'          # Unity Ads
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
